[default]
workshop = [
]

[spe]
extends = "default"
dlc = [
    "Spearhead 1944"
]

[vn]
extends = "default"
dlc = [
    "S.O.G. Prairie Fire",
]

[ws]
extends = "default"
dlc = [
    "Western Sahara",
]

[rf]
extends = "default"
dlc = [
    "Reaction Forces"
]

[gm]
extends = "default"
dlc = [
    "Global Mobilization - Cold War Germany"
]

[rhs]
extends = "default"
workshop = [
]
