name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read
jobs:
  build_addon:
    runs-on: windows-2022
    steps:
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - name: Pull Arma3Tools
      run: |
        echo ${{ secrets.CR_PAT }} | docker login -u ${{ secrets.CR_USER }} --password-stdin ghcr.io
        docker pull ghcr.io/armaforces/arma3tools:v2

    - name: Build using HEMTT
      run: |
        docker run -v "$(pwd):c:/workdir" -e CI=$True ghcr.io/armaforces/arma3tools:v2 hemtt release

    - uses: actions/upload-artifact@4.6.2
      with:
        name: hemttout
        path: .hemttout/
        if-no-files-found: error
        retention-days: 1

    - uses: actions/upload-artifact@4.6.2
      with:
        name: releases
        path: releases/
        if-no-files-found: error
        retention-days: 7

  release_addon:
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-latest
    needs: build_addon
    steps:
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV

    # Upload to GitHub
    - uses: actions/download-artifact@4.2.1
      with:
        name: releases
        path: releases
    - uses: softprops/action-gh-release@v1
      with:
        files: 'releases/uksf taskforce alpha mods_${{ env.VERSION }}*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Upload to Steam Workshop
    - uses: actions/download-artifact@4.2.1
      with:
        name: hemttout
        path: .hemttout
    - uses: arma-actions/workshop-upload@v1
      with:
        itemId: '3462905403' # Id of item to update
        contentPath: '.hemttout/release'
        changelog: 'https://github.com/UKSFTA/UKSFTA-Mods/releases/tag/v${{ env.VERSION }}'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}